### ISSUE TITLE
The event that I receive in my Lambda handler is of type APIGatewayProxyEvent and not APIGatewayProxyEventV2

### ISSUE THREAD

**Issue by saqibarfeen** [MarioSimou/serverless-offline-lambda-function-urls#2]
<img width="1374" alt="gh" src="https://github.com/MarioSimou/serverless-offline-lambda-function-urls/assets/27664866/16b987a7-0d4b-4ea9-80f7-67f382e55b03">

The event that I receieve resembles the [1.0 type](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html) , while in the actual Lambda deployment, the event type is always 2.0.

Any clues why I receieve the old event type?

**Comment by MarioSimou** [comment]
I feel that I am missing some configuration over [here](https://github.com/MarioSimou/serverless-offline-lambda-function-urls/blob/main/index.js#L42). I will come back to you soon

**Comment by MarioSimou** [comment]
@saqibarfeen can you please check v1.0.2? You should receive events on v2.0 format

**Comment by saqibarfeen** [comment]
Yes, now it is v2.0 . Perfect, thank you!
How did you do that?

```json
{
  "body": "{\n    \"userId\": \"p6deghasc2lyubv6y\"\n}",
  "cookies": [
  ],
  "headers": {
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.32.3",
    "accept": "*/*",
    "postman-token": "25b43c08-63ce-4289-81cb-5c12d52b2a64",
    "host": "127.0.0.1:3004",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "63",
  },
  "isBase64Encoded": false,
  "pathParameters": null,
  "queryStringParameters": null,
  "rawPath": "/dev/checkIfUserExists",
  "rawQueryString": "",
  "requestContext": {
    "accountId": "offlineContext_accountId",
    "apiId": "offlineContext_apiId",
    "authorizer": {
      "jwt": {
        "claims": undefined,
        "scopes": undefined,
      },
    },
    "domainName": "offlineContext_domainName",
    "domainPrefix": "offlineContext_domainPrefix",
    "http": {
      "method": "POST",
      "path": "/dev/checkIfUserExists",
      "protocol": "HTTP/1.1",
      "sourceIp": "127.0.0.1",
      "userAgent": "PostmanRuntime/7.32.3",
    },
    "operationName": undefined,
    "requestId": "offlineContext_resourceId",
    "routeKey": "POST /dev/checkIfUserExists",
    "stage": "$default",
    "time": "11/Jul/2023:21:02:01 +0200",
    "timeEpoch": 1689102121688,
  },
  "routeKey": "POST /dev/checkIfUserExists",
  "stageVariables": null,
  "version": "2.0",
}
```

**Comment by MarioSimou** [comment]
[Here](https://github.com/MarioSimou/serverless-offline-lambda-function-urls/commit/76101bede4d89d75800dd47df95d68f1c73eac61) the commit change. I just had to update some of the parameters that I am passing to serverless-offline
